bundles:
    class:
        # Cookie
        Plattry\Http\Cookie\CookieInterface: Plattry\Http\Cookie\Cookie
        Plattry\Http\Cookie\CookieProcessor: Plattry\Http\Cookie\CookieProcessor

        # session
        Plattry\Http\Session\SessionInterface: Plattry\Http\Session\Session
        Plattry\Http\Session\SessionProcessor: Plattry\Http\Session\SessionProcessor
        Plattry\Http\Session\DriverInterface: Plattry\Http\Session\FileDriver

    directory:
        # Http controller, handler
        - app\Http\Controller
        - app\Http\Handler

routes:
    attribute:
        directory:
            - app\Http\Controller

server:
    ip: 0.0.0.0
    port: 9000
    event:
        - App\Http\Handler\ConnectHandler
        - App\Http\Handler\MessageHandler
        - App\Http\Handler\CloseHandler
        - App\Http\Handler\ErrorHandler
